### ISSUE TITLE
A user can calculate a childs BMI

### ISSUE THREAD

**Issue by anthonyrodarte** [anthonyrodarte/BMI#1]
**Motivation** 

A user should be able to input their childs information in order to find out if their placement on the BMI scale.

***Component Hierarchy***
```javascript
<Calculator>
  <Age Input/>
  <Weight Inputs>
  <Height Input/>
</Calculator>
```

**Tasks**

- [x] Set up application environment.
- [x] Build Static Component.
- [x] Component logs BMI into console.
- [ ] Component renders 
- [ ] Style component.
